### ISSUE TITLE
Warning: Missing argument 3 for gf_apply_filters()

### ISSUE THREAD

**Issue by remcotolsma** [wp-pay-extensions/gravityforms#2]
I'm seeing the following error in Gravity Forms version `1.9.14`:

```
Warning: Missing argument 3 for gf_apply_filters(), called in /public_html/wp-content/plugins/pronamic-ideal/vendor/wp-pay-extensions/gravityforms/views/html-admin-feed-settings.php on line 745 and defined in /public_html/wp-content/plugins/gravityforms/gravityforms.php on line 3279
```

https://github.com/wp-pay-extensions/gravityforms/blob/1.6.2/views/html-admin-feed-settings.php#L745

https://github.com/wp-premium/gravityforms/blob/1.9.18/gravityforms.php#L3314-L3347

It looks like the `gf_apply_filters` was changed in version `1.9.15`:
https://github.com/wp-premium/gravityforms/blob/2.0.1/change_log.txt#L366

Before: https://github.com/wp-premium/gravityforms/blob/1.9.13.26/gravityforms.php#L3266-L3288
After: https://github.com/wp-premium/gravityforms/blob/1.9.15/gravityforms.php#L3309-L3342

@rvdsteege is the following line required?

```
$js_form = gf_apply_filters( array( 'gform_admin_pre_render', $form_id ), $js_form );
```

**Comment by rvdsteege** [comment]
Assigning the Javascript `form` variable originates from adding merge tag support to the transaction description field » https://github.com/wp-pay-extensions/gravityforms/commit/46eb6c3a13e6830fe46e1bbeea7c53869ac0751e

It is only needed in Gravity Forms < `1.7`, as we now support payment feeds in form settings – which already assigns the `form` variable by default. I've removed the `gf_apply_filters()` (which was added in Gravity Forms `1.9.3`) and now assign the `form` variable only for Gravity Forms versions < `1.7` » https://github.com/wp-pay-extensions/gravityforms/commit/5149d9c5436aa969a03e3f805be5b5f54b482384

**Comment by rvdsteege** [comment]
This repository is a Gravity Forms extension for the Pronamic Pay payment plugin and unrelated to the _Gravity Forms Entries in Excel_ plugin that you seem to be using. Please see the plugin support forum at https://wordpress.org/support/plugin/gf-entries-in-excel for support.
