### ISSUE TITLE
Problem with gravity forms: Missing argument 3 for gf_apply_filters()

### ISSUE THREAD

**Issue by awezoom** [wp-pay-extensions/gravityforms#3]
Hi. I have a page that has been running with Gravity forms for a couple of years without issues. Now, yesterday I upgraded Wordpress, and now, when I try to download the Excel file, I get these errors:
Warning: Missing argument 3 for gf_apply_filters(), called in /homepages/33/d379022791/htdocs/clickandbuilds/infoclustering/wp-content/plugins/gf-entries-in-excel/src/Repository/FormsRepository.php on line 61 and defined in /homepages/33/d379022791/htdocs/clickandbuilds/infoclustering/wp-content/plugins/Gravityforms.v1.9.4.4/gravityforms.php on line 3131

This appears in the order by area.

But in the end of the page I get this error:
Fatal error: Call to protected method GFAddOn::get_plugin_settings() from context 'GFExcel\Repository\FieldsRepository' in /homepages/33/d379022791/htdocs/clickandbuilds/infoclustering/wp-content/plugins/gf-entries-in-excel/src/Repository/FieldsRepository.php on line 150

I've tried to disable, uninstall and reinstall the plugin, but still found no changes. Any help here? I don't know how to proceed.

Thanks in advance!

**Comment by awezoom** [comment]
Also, I forgot to mention that, when I try to download the excel results, I get this fullscreen message:

Fatal error: Call to protected method GFAddOn::get_plugin_setting() from context 'GFExcel\Repository\FormsRepository' in /homepages/33/d379022791/htdocs/clickandbuilds/infoclustering/wp-content/plugins/gf-entries-in-excel/src/Repository/FormsRepository.php on line 31
Gravity Forms Entries in Excel: Whoops, unfortunately something is broken.

Error message: Call to protected method GFAddOn::get_plugin_setting() from context 'GFExcel\Repository\FormsRepository'

If you need support for this, please contact me via the support forum on the wordpress plugin.

Check if someone else had the same error, before posting a new support question.
And when opening a new question, please use the error message (Call to protected method GFAddOn::get_plugin_setting() from context 'GFExcel\Repository\FormsRepository') as the title,
and include the following details in your message:

Plugin Version: 1.5.3
PHP Version: 5.6.38
Wordpress Version: 4.9.8
Error message: Call to protected method GFAddOn::get_plugin_setting() from context 'GFExcel\Repository\FormsRepository'
Error stack trace:

#0 [internal function]: GFExcel\Renderer\AbstractPHPExcelRenderer->fatal_handler()
#1 {main}

**Comment by rvdsteege** [comment]
This repository is a Gravity Forms extension for the Pronamic Pay payment plugin and unrelated to the _Gravity Forms Entries in Excel_ plugin that you seem to be using. Please see the plugin support forum at https://wordpress.org/support/plugin/gf-entries-in-excel for support.
