### ISSUE TITLE
Error on conditional logic checkbox toggle in payment feed

### ISSUE THREAD

**Issue by jeffreyvr** [wp-pay-extensions/gravityforms#5]
When the checkbox for conditional logic is checked in the payment feed settings (Advanced tab), the following error occurs:

```
TypeError: undefined is not an object (evaluating 'e.conditionalLogic.actionType')
```

This results in the conditional logic options not showing up.

GravityForms v2.5.1
Pronamic Pay v6.7.1 
WordPress v5.7.2

No other plugins are active.

<img width="1886" alt="Screenshot 2021-05-17 at 13 52 34" src="https://user-images.githubusercontent.com/9550079/118484166-3407f680-b717-11eb-83ed-727a492a68a1.png">

**Comment by rvdsteege** [comment]
Known issue (that seems to be introduced _after_ the Gravity Forms 2.5 RC), we're working on a fix.

**Comment by jeffreyvr** [comment]
One thing I noticed was that the checkbox key is now named `_gform_setting_feed_condition_conditional_logic_object` while it was named `_gaddon_setting_feed_condition_conditional_logic_object` before. (https://github.com/wp-pay-extensions/gravityforms/blob/2085c1c7b33108d2c1f28e8b1aa839e652b7e731/src/AdminPaymentFormPostType.php#L377)
